# Generated by Django 4.1.2 on 2022-10-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=45, verbose_name='Apellido')),
                ('domicilio', models.CharField(blank=True, max_length=45, null=True, verbose_name='Domicilio')),
                ('contacto', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tel. de Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('cuit_cuil', models.CharField(max_length=15, verbose_name='CUIT/CUIL')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'db_table': 'propietarios',
                'ordering': ['apellido', 'nombre'],
                'managed': True,
            },
        ),
    ]
