# Generated by Django 4.1.2 on 2022-11-17 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edificios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_codigo', models.CharField(max_length=50, verbose_name='Código Movimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_movim', models.CharField(max_length=4, verbose_name='Año del Movimiento')),
                ('mes_movim', models.CharField(max_length=4, verbose_name='Mes del Movimiento')),
                ('fecha_movim', models.DateField(verbose_name='Fecha Movimiento')),
                ('tipo_movim', models.IntegerField(default=1, verbose_name='Tipo Movimiento')),
                ('detalle_movim', models.CharField(blank=True, max_length=100, null=True, verbose_name='Detalle del Movimiento')),
                ('expensas', models.CharField(choices=[('1', 'Corresponde'), ('2', 'No Corresponde')], max_length=1)),
                ('codigo_movim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.codigomovimiento')),
                ('id_edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.edificios')),
            ],
        ),
    ]
